### ISSUE TITLE
Server Side Plugin

### ISSUE THREAD

**Issue by drav0011** [Kleinrotti/TeamCord#1]
Having this as a server side plugin would be a really good option for some people.

I have knowns who do not want to use TS even if it works better in most scenarios on the calls, and as most of us are in TS and not discord, having a ts server plugin, and a discord bot connected on the other side to crosscall would be the best in my case.

**Comment by Kleinrotti** [comment]
I will look into this. Unfortunately there is no TS Server API, only a Client API. But maybe I could get it to work with some kind of a service which is running on the Linux/Windows Server in the background and interacts as interface between TS and Discord.

**Comment by velotoxicsounds** [comment]
As a plugin for sinusbot, the implementation should be much easier. You only need to create a local stream with your plugin, then stream it via the API to the sinusbot. Your plugin is ready for server-side use
