### ISSUE TITLE
Crash on use Mute Microphone

### ISSUE THREAD

**Issue by 8Christian** [Kleinrotti/TeamCord#10]
TeamSpeak Client 3.5.7
Mute/ Disable Headphone = Crash
[ts3client_2021-03-16__17_49_08.044495.log](https://github.com/Kleinrotti/TeamCord/files/6150821/ts3client_2021-03-16__17_49_08.044495.log)
[ts3dump_1615913363701.zip](https://github.com/Kleinrotti/TeamCord/files/6150824/ts3dump_1615913363701.zip)

**Comment by Kleinrotti** [comment]
Does this happen every time? Are you using a hotkey to mute teamspeak or do you use the buttons in the teamspeak UI? I can't see anything special in the logs so far.

**Comment by 8Christian** [comment]
It happens when you press the hotkey and the button.
It also only happens in the latest beta version of Teamspeak

**Comment by Kleinrotti** [comment]
Please try the appended test version of Teamcord and append the log again.
Just replace the extracted file in %appdata%\TS3Client\plugins\TeamCord.dll
[TeamCord.zip](https://github.com/Kleinrotti/TeamCord/files/6158973/TeamCord.zip)

**Comment by 8Christian** [comment]
[ts3client_2021-03-18__17_32_40.372858.log](https://github.com/Kleinrotti/TeamCord/files/6165697/ts3client_2021-03-18__17_32_40.372858.log)

**Comment by Kleinrotti** [comment]
I found the issue, this happens only if you are not logged in to discord.
Will be fixed in the next release.

**Comment by 8Christian** [comment]
Thank you very much
