### ISSUE TITLE
Login bug

### ISSUE THREAD

**Issue by flamesv** [Kleinrotti/TeamCord#11]
Hi, I have a problem
```
2021-03-23 16:27:18.656803|INFO    |TeamCord      |   |Requesting login token
2021-03-23 16:27:19.313397|ERROR   |TeamCord      |   |Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.
```
 that due to the fact that captcha is not sent, the plugin cannot authorize, a message is returned that captcha is required (viewed by a sniffer), I tried to manually add the token to the configuration file, it did not work, error, I then I realized that the token is encrypted. Is it possible to somehow solve this?, maybe there is a version where you can manually enter the token?
```2021-03-23 15: 52: 32.460092 | ERROR | TeamCord | | Conversion error for the value 'MzQ0MDc2 ** U06 *** ODkyO24y. ****. 25wc2PB3V *** yfkYoVtTv1Vd2E "to the" TeamCord.Core.PluginUserCredential "type. The 'Token' path, line 2, position 72. ```

**Comment by Kleinrotti** [comment]
Please login at discord.com first to solve a captcha. The login to Teamcord should work afterwards.

**Comment by flamesv** [comment]
> Please login at discord.com first to solve a captcha. The login to Teamcord should work afterwards.

in my case, this did not solve the problem, there is a suspicion that now the discord asks for captcha input every time, and not only when suspicious actions.

**Comment by flamesv** [comment]
Fixed the problem by registering a new account, it did not ask for confirmation of the captcha during authorization.
