### ISSUE TITLE
Output device selection

### ISSUE THREAD

**Issue by julianbartel** [Kleinrotti/TeamCord#12]
**Describe the bug**
TeamCord plugin does not respect audio device selection from TeamSpeak

**To Reproduce**
In TeamSpeak, configure an output device which is not the default device.

**Expected behavior**
Voice of TeamCord shourd come from the same output device as other TeamSpeak voice.

**Screenshots**
n/a

**Desktop:**
 - Teamspeak 3 Version: 3.5.6
 - Plugin Version 0.1.2.1
 
**Additional context**
Bug has been reported by someone in our community, I did not have a chance to reproduce it on my own, so I hope information is sufficient. Let me know if anything is missing.

**Comment by Kleinrotti** [comment]
This isn't a bug, Teamcord currently does not have an option to select an audio output device. It uses the default windows audio device. Maybe I will add an option to select the device in the future.

**Comment by julianbartel** [comment]
Agreed with the categorization.
I am currently preparing a PR, though that might take some time (need to get familiar with the code base first).

**Comment by Kleinrotti** [comment]
In the next release this will be added to TeamCord. TeamCord uses the audio output which is selected in Teamspeak itself then.

**Comment by Kleinrotti** [comment]
Released in version 0.1.3.0.
