### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by KaratekHD** [Kleinrotti/TeamCord#13]
**Describe the solution you'd like**
I'd like to have the ability to use this Plugin on my Linux PC.

**Describe alternatives you've considered**
Maybe it is possible to build a standalone version the way https://github.com/Splamy/TS3AudioBot does it?

**Comment by Kleinrotti** [comment]
This not possible, because TeamCord is a dll which is loaded by Teamspeak. This unfortunately only works on windows with C#.

**Comment by KaratekHD** [comment]
Ok, that's sad, but thank you anyway
