### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by Bealze** [Kleinrotti/TeamCord#15]
after latest install as soon as i start TeamSpeak it crashes have tried uninstall and reinstall same result worked prier version

**Comment by Kleinrotti** [comment]
Please append the teamspeak logfile.
Location: %appdata%\TS3Client\logs

**Comment by Bealze** [comment]
@Kleinrotti 
[ts3client_2021-09-06__13_33_17.413958.log](https://github.com/Kleinrotti/TeamCord/files/7117318/ts3client_2021-09-06__13_33_17.413958.log)

**Comment by Kleinrotti** [comment]
Fixed in version 0.1.3.1.
