### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by cj0duke** [Kleinrotti/TeamCord#2]
Unable to get connectoin to discord (debug logging enabled). After setting log credentials, login shows successful. But can not connect to discord.

**Desktop (please complete the following information):**
 - Teamspeak 3 Version: 3.5.5
 - Plugin Version 0.1.1.1

Teamspeak log:```
20.11.2020 11:09:24	TeamCord	Info	Waiting for established connection to discord...	
20.11.2020 11:09:24	TeamCord	Info	Client disconnected	
20.11.2020 11:09:24	TeamCord	Debug	Updating icon of tray icon	
20.11.2020 11:09:24	TeamCord	Debug	Connection changed -> Type: Discord Connected: False	
20.11.2020 11:09:24	TeamCord	Debug	Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.	
20.11.2020 11:09:24	TeamCord	Debug	Freeing memory: 177919312	
20.11.2020 11:09:24	TeamCord	Warning	Unexpected character encountered while parsing value: W. Path '', line 0, position 0.	
20.11.2020 11:09:24	TeamCord	Debug	Freeing memory: 176352064	
20.11.2020 11:09:24	TeamCord	Warning	Unexpected character encountered while parsing value: W. Path '', line 0, position 0.	
20.11.2020 11:09:24	TeamCord	Debug	Freeing memory: 177928912	
20.11.2020 11:09:25	TeamCord	Info	Client disconnected	
20.11.2020 11:09:25	TeamCord	Debug	Updating icon of tray icon	
20.11.2020 11:09:25	TeamCord	Debug	Connection changed -> Type: Discord Connected: False	
20.11.2020 11:09:27	TeamCord	Info	Client disconnected	
20.11.2020 11:09:27	TeamCord	Debug	Updating icon of tray icon	
20.11.2020 11:09:27	TeamCord	Debug	Connection changed -> Type: Discord Connected: False	
20.11.2020 11:09:31	TeamCord	Info	Client disconnected	
20.11.2020 11:09:31	TeamCord	Debug	Updating icon of tray icon	
20.11.2020 11:09:31	TeamCord	Debug	Connection changed -> Type: Discord Connected: False	
20.11.2020 11:09:40	TeamCord	Info	Client disconnected	

```

**Comment by Kleinrotti** [comment]
Did you restart Teamspeak after entering the discord credentials? If yes, please attach a full ts3 log file.
