### ISSUE TITLE
Features!

### ISSUE THREAD

**Issue by snaildos** [Kleinrotti/TeamCord#3]
**Is your feature request related to a problem? Please describe.**
Using user tokens is against TOS!!!!! Will you be adding bot support?
Just so we can add a bot token, invite the bot, and it works?

**Describe the solution you'd like**
I think this would be perfect. I don't mind that.

**Describe alternatives you've considered**
This is the only thing I found to link the two together, I don't want to get banned. 

**Additional context**

**Comment by Kleinrotti** [comment]
When using a bot, many features are not possible to implement.
One example, if there are multiple TeamCord users which want to crosstalk to a discord channel on the same server, this would be impossible because the bot can only connect to one channel at the same time on the server.

**Comment by snaildos** [comment]
:( I don't understand,
I only want crosstalk from teamspeak --> discord.
Have a discord bot in one channel, syncing sound to a teamspeak channel.
