### ISSUE TITLE
Teamspeak crash after right click to any channel

### ISSUE THREAD

**Issue by code-dep** [Kleinrotti/TeamCord#4]

**Comment by Kleinrotti** [comment]
This could only happen after entering the discord credentials without restarting Teamspeak. If this happens after a teamspeak restart attach the ts3 log file please.

**Comment by Kleinrotti** [comment]
I was able to reproduce this. Will be fixed in the next release.

**Comment by Kleinrotti** [comment]
Fixed in version 0.1.2.0.
