### ISSUE TITLE
deletes all preset channel info

### ISSUE THREAD

**Issue by Bealze** [Kleinrotti/TeamCord#5]
when you sync a channel if the description had info it deletes it all found out the hard way

**Comment by Kleinrotti** [comment]
Yes all other description texts will be removed, otherwise TeamCord can't detect the created json string correctly.

**Comment by Bealze** [comment]
ok darn there goes that idea. any way to set it to just add the line of infor ?id like to use this but i cant if its going to remove the descriptions on any channel i would link

**Comment by Kleinrotti** [comment]
In the next release the ts3 channel description will be no longer removed. Instead the json string will appended.

**Comment by Bealze** [comment]
well sweet i will give it a shot for ya as soon as i see it published or pushed

**Comment by Kleinrotti** [comment]
Implemented since version 0.1.2.0
