### ISSUE TITLE
is there a fix in the works for 

### ISSUE THREAD

**Issue by Bealze** [Kleinrotti/TeamCord#6]
Only this json string should be in the channel description otherwise it couldn't be recognized by TeamCord!

the channel decryptions are a big part of mine and many servers can you teach it to ignore anything after its {"Teamcord":{"Channel":000000000}} /n/n

or somen to allow it to just check for its needed string in only the top line or last line type thing?

**Comment by Kleinrotti** [comment]
Same as this [#5](https://github.com/Kleinrotti/TeamCord/issues/5)
In the next release you can copy that json string wherever you want in the description. Teamcord will find it.
