### ISSUE TITLE
Sound Problems

### ISSUE THREAD

**Issue by 72Joe72** [Kleinrotti/TeamCord#7]
I, (and my freinds) have a problem with the sound or voice

From Discord to TeamSpeak everything is ok, 
but the Discord users hear my voce like a Robot

**Here is the log
i removed the timestamp ect (2021-01-19 XX:XX:XX.XXXXXX|INFO    |TeamCord      |   )

> |Waiting for established connection to discord...
|Connection changed -> Type: Discord Connected: True
|Client connected
|Updating icon of tray icon
|Connection established to discord
|Joining discord channel 239104154914521089
|Client connected to voice
|Updating icon of tray icon
|Connection changed -> Type: Voice Connected: True
|Applying ts3 mute state...
|Updating icon of tray icon
|Updating icon of tray icon
|Current ts3 mute state: Deaf=0 Mute=0
|Voice processing time: 343us
|Wave device -1 initialized. Samplerate: 48000 Channels: 2
|SoundService loaded for user Joe_72
|Playback started of user Joe_72
|Voice processing time: 105us
|Voice processing time: 126us
|Voice processing time: 109us
|Voice processing time: 113us
|Voice processing time: 105us
|Voice processing time: 112us
|Voice processing time: 134us
|Voice processing time: 99us
|Voice processing time: 131us
|Voice processing time: 106us
|Voice processing time: 135us
|Voice processing time: 123us
|Voice processing time: 100us
|Voice processing time: 126us
|Voice processing time: 140us
|Voice processing time: 125us
|Voice processing time: 136us
|Voice processing time: 127us
|Voice processing time: 137us
|Voice processing time: 124us
|Voice processing time: 102us
|Voice processing time: 127us
|Voice processing time: 131us
|Voice processing time: 123us
|Voice processing time: 134us
|Voice processing time: 124us
|Voice processing time: 132us
|Voice processing time: 96us
|Voice processing time: 137us
|Voice processing time: 123us
|Voice processing time: 137us
|Voice processing time: 99us
|Voice processing time: 122us
|Voice processing time: 95us
|Voice processing time: 123us
|Voice processing time: 124us
|Voice processing time: 132us
|Voice processing time: 124us
|Voice processing time: 135us
|Voice processing time: 96us
|Voice processing time: 134us
|Voice processing time: 124us
|Voice processing time: 134us
|Voice processing time: 106us
|Voice processing time: 117us
|Voice processing time: 112us
|Voice processing time: 119us
|Voice processing time: 116us
|Voice processing time: 139us
|Voice processing time: 125us
|Voice processing time: 101us
|Voice processing time: 116us
|Voice processing time: 115us

**Comment by Kleinrotti** [comment]
Voice processing times look good so far. Does this distorted audio only happen the first seconds after you joined the discord channel or all the time?

**Comment by 72Joe72** [comment]
It's all the time -.-

**Comment by Kleinrotti** [comment]
This seems more like a problem with your internet connection in the upstream. Robot voice is a strong indicator for a high packet loss in the internet upstream. Maybe you could try the discord app itself and check if it's happen there too. I'm currently try to add a packet loss indicator to TeamCord like the discord app does for better debugging, but it will take some days.

**Comment by 72Joe72** [comment]
I tried it on the Discord app, works fine. Same on Teamspeak

**Comment by 8Christian** [comment]
As soon as you set the channel quality to "Opus Music", it also happens that you are no longer understood in Discord.

**Comment by 72Joe72** [comment]
@8Christian thanks, now it works clear ^^

**Comment by nike4613** [comment]
I am seeing this issue still happen with the voice channel set to Opus Voice at quality 6.

**Comment by Kleinrotti** [comment]
When using Opus Voice sound is fine on my side (when the channel was set to Opus Music before, you have to restart Teamspeak to apply the setting for Teamcord). I think I found the issue with Opus Music. When using Opus Voice, Teamspeak sends the raw float audio with 1 audio channel so Teamcord has to convert it to stereo audio for Discord. But when using Opus Music, Teamspeak sends the raw float audio as stereo audio so the conversion is broken. I will release a fix soon.

**Comment by Kleinrotti** [comment]
Fixed in version 0.1.2.2.
