### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by 8Christian** [Kleinrotti/TeamCord#8]
Teamspeak Version
3.5.6 (25.11.2020 14:53:42)

TeamCord Version
0.1.2.0

Discord
Stable 77645 (6bbb9a6)
Host 0.0.308

Windows 10 64-Bit (10.0.19042)
Version 20H2 (Build 19042.844)

Client Log
26.02.2021 18:20:34	TeamCord	Info	Config file does not exists, creating one...	
26.02.2021 18:20:34	TeamCord	Info	Storing plugin settings...	
26.02.2021 18:20:34	TeamCord	Info	Reading plugin settings...	
26.02.2021 18:20:34	TeamCord	Info	TeamCord 0.1.2.0	
26.02.2021 18:20:34	TeamCord	Info	Runtime CLR: 4.0.30319.42000	
26.02.2021 18:20:35	TeamCord	Info	Tray icon loaded	
26.02.2021 18:20:35	TeamCord	Info	Teamcord initialized in 566ms	
26.02.2021 18:30:25	TeamCord	Info	Requesting login token	
26.02.2021 18:30:26	TeamCord	Error Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.

Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
The remote server has returned an error: (400) Invalid request.

Image:
![TeamCord](https://user-images.githubusercontent.com/79718891/109341869-505c6b80-786b-11eb-99ac-74ec4993df17.PNG)

Two-factor authentication (2FA) was disable

Password and username were copied in

**Comment by Kleinrotti** [comment]
Have you tried to login at discord.com first and solve the captcha there?

**Comment by 8Christian** [comment]
Yes. I used Firefox for my default browser. I have also tried with several accounts.

**Comment by Kleinrotti** [comment]
Please enable debug mode in the Teamcord settings and post the log again here with the error.

**Comment by 8Christian** [comment]
As soon as I go setting, the login window comes. 
![Teamcord_1](https://user-images.githubusercontent.com/79718891/109388309-9b778c80-7906-11eb-9b75-8f5de0f1496a.png)
![Teamcord_2](https://user-images.githubusercontent.com/79718891/109388310-9c102300-7906-11eb-93a4-8e81d91357c3.PNG)
![Teamcord_3](https://user-images.githubusercontent.com/79718891/109388311-9c102300-7906-11eb-990d-779eb07067b6.PNG)

**Comment by Kleinrotti** [comment]
Open this file: %appdata%\TS3Client\plugins\TeamCord\config.json
Set the entry DebugLogging from false to true

**Comment by 8Christian** [comment]
2021-02-27 14:16:49.097375|INFO    |TeamCord      |   |Requesting login token
2021-02-27 14:16:50.058077|ERROR   |TeamCord      |   |Exception: Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
                                                       Stacktrace:    bei System.Net.HttpWebRequest.GetResponse()
                                                          bei TeamCord.Core.Auth.RequestToken()

**Comment by Kleinrotti** [comment]
Unfortunately I can't reproduce this with my two accounts, both are working. Error 400 Bad request generally means that the credentials are wrong (or the username is used at login instead of the email) or discord blocks the login for some reason e.g. a new IP address or too many failed attempts. 
The discord login in the browser works fine right? If yes, you could try to enable 2fa authentication. If that does not work too, I have no clue.

**Comment by 8Christian** [comment]
The login data are copied therefore I exclude an input error.
2fa authentication is enable
In the browser I can log in without any problems.
Edit: I have created a new account with these I could log in
