### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by 8Christian** [Kleinrotti/TeamCord#9]
- The settings of the "Volume Control" are not saved.
- After some time you will be thrown from Discord for no reason inactive or not.

**Comment by Kleinrotti** [comment]
I will try to reproduce the second one. What would help, if you enable debug logging in the teamcord settings and append the teamspeak log file (%appdata%\TS3Client\logs) when this happens again.

**Comment by 8Christian** [comment]
Debug I have still switched on. As soon as it happens again I will provide the logs.
